version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  chromadb:
    build:
      context: ./chromadb
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; exit(0) if urllib.request.urlopen('http://localhost:8000/api/v1/heartbeat').status==200 else exit(1)"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 120s
#32:     # command: sh -c "uvicorn chromadb.app:app --host 0.0.0.0 --port 8000"

  aurora-core:
    build: .
    container_name: aurora-core
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: uvicorn src.aurora_platform.main:app --host 0.0.0.0 --port 8080 --reload
    depends_on:
      redis:
        condition: service_healthy
      chromadb:
        condition: service_healthy

volumes:
  redis_data:
  chroma_data:
