services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  chromadb:
    image: chromadb/chroma:0.5.20
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma

  aurora-core:
    build: .
    container_name: aurora-core
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - chromadb
    # volumes:
    #   - .:/app

volumes:
  redis_data:
  chroma_data:
