version: '3.8'

services:
  aurora-core:
    # Usa o estágio 'builder' do nosso Dockerfile, que contém as ferramentas de desenvolvimento
    build:
      context: .
      target: builder
    volumes:
      - .:/app
    command: ["uvicorn", "src.aurora_platform.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
