
services:
  redis:
    image: redis:7.0-alpine
    container_name: aurora-redis
    networks:
      - aurora-net
    ports:
      - "6379:6379"

  aurora-core:
    build:
      context: .
      dockerfile: ./aurora-core/Dockerfile
    container_name: aurora-core
    networks:
      - aurora-net
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  aurora-crawler:
    build:
      context: .
      dockerfile: ./aurora-crawler/Dockerfile
    container_name: aurora-crawler
    networks:
      - aurora-net
    env_file: .env
    ports:
      - "8001:8001"
    depends_on:
      - redis

networks:
  aurora-net:
    driver: bridge
