services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: aurora-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - aurora-net

  gpt-oss:
    build:
      context: .
      dockerfile: ./gpt-oss/Dockerfile
    container_name: aurora-gpt-oss
    ports:
      - "8002:8002"
    networks:
      - aurora-net

  aurora-core:
    build:
      context: .
      dockerfile: ./aurora-core/Dockerfile
    container_name: aurora-core
    ports:
      - "8008:8000"
    networks:
      - aurora-net
    depends_on:
      - qdrant
      - gpt-oss

  aurora-crawler:
    build:
      context: .
      dockerfile: ./aurora-crawler/Dockerfile
    container_name: aurora-crawler
    ports:
      - "8001:8001"
    networks:
      - aurora-net
    depends_on:
      - qdrant
      - gpt-oss

volumes:
  qdrant_data:

networks:
  aurora-net:
    driver: bridge
