services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: aurora-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - aurora-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/cluster"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  aurora-core:
    build:
      context: .
      dockerfile: ./aurora-core/Dockerfile
    container_name: aurora-core
    ports:
      - "8008:8000"
    networks:
      - aurora-net
    depends_on:
      qdrant:
        condition: service_healthy

  aurora-crawler:
    build:
      context: .
      dockerfile: ./aurora-crawler/Dockerfile
    container_name: aurora-crawler
    ports:
      - "8001:8001"
    networks:
      - aurora-net
    depends_on:
      qdrant:
        condition: service_healthy

volumes:
  qdrant_data:

networks:
  aurora-net:
    driver: bridge
