version: "3.8"

services:
  # Serviço do Aurora-CRM (Core)
  aurora-crm:
    build:
      context: ./aurora-crm
      dockerfile: Dockerfile
    container_name: aurora-crm
    ports:
      - "8000:8000"
    volumes:
      - ./aurora-crm:/app
    networks:
      - aurora-net
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/auroracrmdb

  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: aurora-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auroracrmdb
    ports:
      - "5432:5432"
    networks:
      - aurora-net

  aurora-qdrant:
    image: qdrant/qdrant:latest
    container_name: aurora-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:6333/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - aurora-net

networks:
  aurora-net:
    driver: bridge

volumes:
  postgres_data:
