version: "3.8"

version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:v1.10.0
    container_name: aurora-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"   # HTTP API
      - "6334:6334"   # gRPC (opcional)
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/readyz"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - aurora-net

  aurora-core:
    build:
      context: .
      dockerfile: ./aurora-core/Dockerfile
    container_name: aurora-core
    restart: unless-stopped
    environment:
      QDRANT_URL: http://qdrant:6333
    ports:
      - "8008:8000"
    depends_on:
      qdrant:
        condition: service_healthy
    networks:
      - aurora-net

networks:
  aurora-net:
    driver: bridge

volumes:
  qdrant_storage:
    driver: local
