[tool.poetry]
name = "aurora-core"
version = "0.1.0"
description = "Aurora Platform - Fábrica de IA"
authors = ["Aurora Team"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.0"
uvicorn = "^0.32.0"
python-multipart = "^0.0.9"
dynaconf = "^3.2.0"
pydantic = "^2.0.0"
python-jose = "^3.3.0"
passlib = "^1.7.4"
bcrypt = "^4.0.0"
google-cloud-aiplatform = "^1.58.0"
firecrawl-py = "^1.5.0"
chromadb = "^1.0.9"
langchain = "^0.3.26"
langchain-community = "^0.3.27"
langchain-google-vertexai = "^2.0.0"
sentence-transformers = "^5.0.0"
pyyaml = "^6.0.0"
streamlit = "^1.28.0"
langchain-huggingface = "^0.3.0"
langchain-chroma = "^0.2.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["src"]
exclude = ["**/node_modules", "**/__pycache__", "src/experimental"]
reportMissingImports = true
pythonVersion = "3.11"
extraPaths = ["src"]