[build-system]
requires = ["poetry-core>=1.7.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "aurora-core"
version = "0.1.0"
description = "Aurora-Core: O Kernel do Sistema Operacional de IA (AIOS) Aurora"
authors = ["Equipe Aurora <dev@aurora.ai>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "aurora_platform", from = "aurora-core/src" }]

[tool.poetry.dependencies]
firebase-admin = "==6.5.0"
python = ">=3.11,<4.0"
fastapi = ">=0.110.0,<0.111.0"
sqlmodel = ">=0.0.16,<0.0.17"
alembic = ">=1.13.1,<2.0.0"
uvicorn = ">=0.29.0,<0.30.0"
pydantic = ">=2.0.0,<3.0.0"
dynaconf = ">=3.2.4,<4.0.0"
passlib = ">=1.7.4,<2.0.0"
python-jose = ">=3.3.0,<4.0.0"
beautifulsoup4 = ">=4.12.3,<5.0.0"
undetected-chromedriver = ">=3.5.5,<4.0.0"
pybreaker = ">=1.1.0,<2.0.0"
tenacity = ">=8.2.3,<9.0.0"
async-lru = ">=2.0.4,<3.0.0"
sentry-sdk = {version = ">=2.6.0,<3.0.0", extras = ["fastapi"]}
slowapi = ">=0.1.9,<0.2.0"
pydantic-settings = ">=2.10.1,<3.0.0"
qdrant-client = ">=1.15.0,<2.0.0"
numpy = ">=2.3.2,<3.0.0"
googleapis-common-protos = ">=1.70.0,<2.0.0"
google-auth = ">=2.40.3,<3.0.0"
distro = ">=1.9.0,<2.0.0"
python-multipart = ">=0.0.20,<0.0.21"
langchain = ">=0.2.0"
langchain-google-vertexai = ">=1.0.3"
langchain-openai = ">=0.1.8"
langchain-deepseek = ">=0.0.2"
httpx = {version = ">=0.28.1", extras = ["http2"]}
pyotp = "^2.9.0"
qrcode = {extras = ["pil"], version = "^8.2"}
pymupdf = "^1.26.3"
openai = "^1.97.1"
redis = "^6.2.0"
chromadb = "^1.0.15"
sentence-transformers = "^5.0.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.2.0,<9.0.0"
pytest-asyncio = ">=0.23.6,<0.24.0"
black = ">=24.4.2,<25.0.0"
ruff = ">=0.4.3,<0.5.0"
pre-commit = ">=3.7.0,<4.0.0"
isort = ">=5.13.2,<6.0.0"

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "W", "I"]


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "aurora-core/tests",
]
pythonpath = [
    "aurora-core/src"
]
