# pyproject.toml - Versão Modernizada (PEP 621)

[tool.poetry]
name = "aurora-core"  # Mantido para compatibilidade com alguns plugins
packages = [{ include = "aurora_platform", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
uvicorn = { extras = ["standard"], version = "^0.29.0" }
sqlmodel = "^0.0.19"
alembic = "^1.13.1"
psycopg2-binary = "^2.9.9"
python-jose = { extras = ["cryptography"], version = "^3.3.0" }
passlib = { extras = ["bcrypt"], version = "^1.7.4" }
python-multipart = "^0.0.9"
pydantic-settings = "^2.3.4"
google-cloud-aiplatform = "^1.58.0"
# Adicione aqui outras dependências de produção se necessário

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pytest-cov = "^5.0.0"
flake8 = "^7.1.0"
# Adicione aqui outras dependências de desenvolvimento se necessário

# --- SEÇÃO [project] PADRÃO (PEP 621) ---
[project]
name = "aurora-core"
version = "0.1.0"
description = "O núcleo da plataforma Aurora, contendo a lógica de negócio, segurança e o cérebro de IA."
authors = [
    { name = "Aurora Labs", email = "contato@auroracrm.com.br" },
]
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
# --- FIM DA NOVA SEÇÃO ---

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["src"]
extraPaths = ["src"]