[tool.poetry]
name = "aurora-core"
version = "0.1.0"
description = "Aurora Platform - Fábrica de IA"
authors = ["Aurora Team"]
readme = "README.md"
packages = [{include = "aurora_platform", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.0"
uvicorn = "^0.32.0"
python-multipart = "^0.0.9"
dynaconf = "^3.2.0"
pydantic = "^2.0.0"
python-jose = "^3.3.0"
passlib = "^1.7.4"
bcrypt = "^4.0.0"
google-cloud-aiplatform = "^1.58.0"
chromadb = "^1.0.9"
langchain = "^0.3.26"
langchain-community = "^0.3.27"
langchain-google-vertexai = "^2.0.0"
sentence-transformers = "^5.0.0"
pyyaml = "^6.0.0"
openai = "^1.93.0"
tenacity = "^9.0.0"
streamlit = "^1.28.0"
langchain-huggingface = "^0.3.0"
langchain-chroma = "^0.2.4"
protobuf = "^4.21.6"
undetected-chromedriver = "^3.5.5"
beautifulsoup4 = "^4.13.4"
numpy = "^2.3.1"
requests = "^2.31.0"
selenium = "^4.34.2"
async-lru = "^2.0.5"
firecrawl-py = "^2.15.0"
locust = "^2.37.12"
pymupdf = "^1.23.24"
langchain-openai = "^0.3.27"
httpx = "^0.28.1"

[tool.poetry.group.dev.dependencies]
bandit = "^1.8.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["src"]
exclude = ["**/node_modules", "**/__pycache__", "src/experimental"]
reportMissingImports = true
pythonVersion = "3.11"
extraPaths = ["src"]

