[tool.poetry]
name = "aurora-platform"
version = "0.1.0"
description = "Aurora Platform - IA integrada com GCP e NLP"
authors = ["Aurora Team <team@auroracrm.com.br>"]
packages = [{ include = "aurora_platform", from = "src" }]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.30.1"}
sqlmodel = "^0.0.18"
alembic = "^1.13.1"
python-dotenv = "^1.1.1"
google-generativeai = "^0.3.2"
google-cloud-aiplatform = "^1.100.0"
chromadb = "^1.0.13"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
pydantic-settings = "^2.10.1"
psycopg2-binary = "^2.9.10"
redis = "^6.2.0"
aioredis = "^2.0.0"
pyotp = "^2.9.0"
qrcode = {extras = ["pil"], version = "^7.4.2"}
pyyaml = "^6.0.1"
sentence-transformers = "^4.1.0"
faiss-cpu = "^1.11.0"
azure-identity = "^1.23.0"
azure-keyvault-secrets = "^4.10.0"
python-box = "^7.3.2"
gunicorn = "^22.0.0"
python-multipart = "^0.0.7"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-cov = "^5.0.0"
pytest-asyncio = "^1.0.0"
httpx = "^0.27.0"
ruff = "^0.1.15"
black = "^24.1.1"
flake8 = "^7.1.0"
bandit = "^1.7.9"
mypy = "^1.11.0"
pyright = "^1.1.402"

[tool.pytest.ini_options]
pythonpath = ["src"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
