[tool.poetry]
name = "aurora-core"
version = "0.1.0"
description = "Aurora-Core: O Kernel do Sistema Operacional de IA (AIOS) Aurora"
authors = ["Equipe Aurora <dev@aurora.ai>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "aurora_platform", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.0"
sqlmodel = "^0.0.16"
alembic = "^1.13.1"
uvicorn = "^0.29.0"
chromadb = "0.4.15"
pydantic = "^2.0.0"
dynaconf = "^3.2.4"
passlib = "^1.7.4"
python-jose = "^3.3.0"
httpx = "^0.27.0"
beautifulsoup4 = "^4.13.0"
undetected-chromedriver = "^3.5.5"
pybreaker = "^1.4.0"
tenacity = "^8.2.3"
async-lru = "^2.0.4"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
pytest-asyncio = "^0.23.6"
black = "^24.4.2"
ruff = "^0.4.3"
pre-commit = "^3.7.0"
httpx = { version = "^0.27.0", extras = ["http2"] }
isort = "^5.13.2"

[build-system]
requires = ["poetry-core>=1.7.0"]
build-backend = "poetry.core.masonry.api"