# Exemplo de estrutura para config/settings.toml
# Copie este arquivo para settings.toml e ajuste os valores

[default]
# Configurações do Projeto
PROJECT_NAME = "Aurora Platform"
PROJECT_VERSION = "0.1.0"

# Configurações de Segurança
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_DAYS = 7
ALLOWED_ORIGINS = []
HTTPS_ONLY = false
MIN_PASSWORD_LENGTH = 8
REQUIRE_UPPERCASE = true
REQUIRE_LOWERCASE = true
REQUIRE_NUMBERS = true
REQUIRE_SPECIAL_CHARS = true
LOGIN_RATE_LIMIT_PER_MINUTE = 5
RATE_LIMIT_PER_MINUTE = 20

# Configurações do Google Cloud
GOOGLE_CLOUD_PROJECT = "your-gcp-project-id"
GOOGLE_CLOUD_LOCATION = "us-central1"

# Configurações do Redis
REDIS_URL = "redis://localhost:6379/0"

[development]
# Configurações específicas para desenvolvimento
HTTPS_ONLY = false
RATE_LIMIT_PER_MINUTE = 10

[production]
# Configurações específicas para produção
HTTPS_ONLY = true
RATE_LIMIT_PER_MINUTE = 100
LOGIN_RATE_LIMIT_PER_MINUTE = 10