name: Agent Packager

on:
  push:
    branches: [ main ]
    paths:
      - 'src/agents/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/agents/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Package agents
        run: |
          poetry run python scripts/package_agents.py

      - name: Upload agent packages
        uses: actions/upload-artifact@v3
        with:
          name: agent-packages
          path: dist/agents/
