name: CI Alerts

on:
  workflow_run:
    workflows: ["CI Aurora-Plataforma"]
    types:
      - completed

jobs:
  slack_notification:
    name: Slack Notification on Failure
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "🚨 Falha no build: ${{ github.event.workflow_run.name }}. Verifique os logs: ${{ github.event.workflow_run.html_url }}"
          SLACK_COLOR: danger

  email_notification:
    name: Email Notification on Failure
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_APP_PASSWORD }}
          subject: "🚨 Falha no CI Aurora Platform"
          to: dev-alerts@aurora.ai
          from: Aurora CI/CD <${{ secrets.EMAIL_USER }}>
          body: |
            O workflow '${{ github.event.workflow_run.name }}' falhou.
            Verifique os logs em: ${{ github.event.workflow_run.html_url }}
