---
name: Aurora Platform CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-core:
    name: Test Aurora Core
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: aurora-core/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-core

      - name: Install dependencies
        working-directory: ./aurora-core
        run: poetry install --no-interaction --no-ansi

      - name: Code quality - Black
        working-directory: ./aurora-core
        run: poetry run black --check .

      - name: Code quality - Ruff
        working-directory: ./aurora-core
        run: poetry run ruff check .

      - name: Run tests
        working-directory: ./aurora-core
        run: poetry run pytest -v

  test-crawler:
    name: Test Aurora Crawler
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: aurora-crawler/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-crawler

      - name: Install dependencies
        working-directory: ./aurora-crawler
        run: poetry install --no-interaction --no-ansi

      - name: Code quality - Black
        working-directory: ./aurora-crawler
        run: poetry run black --check .

      - name: Code quality - Ruff
        working-directory: ./aurora-crawler
        run: poetry run ruff check .

      - name: Run tests
        working-directory: ./aurora-crawler
        run: poetry run pytest -v
